"""Describe your changes

Revision ID: 28c7cf282740
Revises: 32213db73b55
Create Date: 2024-07-31 17:52:46.787899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28c7cf282740'
down_revision: Union[str, None] = '32213db73b55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flights', sa.Column('departure_location', sa.String(), nullable=True))
    op.add_column('flights', sa.Column('arrival_location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flights', 'arrival_location')
    op.drop_column('flights', 'departure_location')
    # ### end Alembic commands ###
