"""Describe your changes

Revision ID: e06738cb1127
Revises: 8926059d17f0
Create Date: 2024-07-31 17:38:17.954498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e06738cb1127'
down_revision: Union[str, None] = '8926059d17f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flights', 'departure_location')
    op.drop_column('flights', 'arrival_location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flights', sa.Column('arrival_location', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('flights', sa.Column('departure_location', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
